"""
strategy/session_bias.py - Voter 5: Time / Session Bias

Loads best_hours.json (generated by the backtest engine).
BUY  vote during hours with historical WR >= 50% (n >= 50 trades).
SELL vote during hours with historical WR <= 40% (n >= 50 trades).
Abstains  during neutral hours or hours with insufficient sample size.

This voter can abstain — when it does, the vote threshold drops from 4/5 to 3/4.
"""

import json
import os
import pandas as pd
from utils.logger import setup_logger

logger = setup_logger("session_bias")

_HOURS_CACHE: dict | None = None
MIN_SAMPLE   = 50
BULL_THRESH  = 50.0
BEAR_THRESH  = 40.0

_HOURS_FILE = os.path.join(os.path.dirname(__file__), "..", "best_hours.json")


def _load_hours() -> dict:
    global _HOURS_CACHE
    if _HOURS_CACHE is None:
        try:
            with open(_HOURS_FILE) as f:
                _HOURS_CACHE = json.load(f)
        except Exception:
            _HOURS_CACHE = {}
    return _HOURS_CACHE


def get_signal(df: pd.DataFrame) -> tuple[int, str]:
    try:
        hour  = int(df.index[-1].hour)
        hours = _load_hours()
        data  = hours.get(str(hour), {})
        wr    = float(data.get("win_rate", 0))
        n     = int(data.get("trades", 0))

        if n < MIN_SAMPLE:
            return 0, f"hour_{hour}_small_sample_n={n}"
        if wr >= BULL_THRESH:
            return 1, f"hour_{hour}_bullish_wr={wr:.1f}%_n={n}"
        if wr <= BEAR_THRESH:
            return -1, f"hour_{hour}_bearish_wr={wr:.1f}%_n={n}"
        return 0, f"hour_{hour}_neutral_wr={wr:.1f}%"

    except Exception as e:
        logger.debug(f"Session bias error: {e}")
        return 0, "session_bias_error"
