"""
utils/session_filter.py

Two-layer session filtering:

Layer 1 — Time windows: blocks trading outside London/NY sessions (UTC)
Layer 2 — Hour filter: only trades during hours with proven win rate
          Reads from best_hours.json generated by the backtester.
          If best_hours.json doesn't exist, falls back to Layer 1 only.
"""

import os
import json
from datetime import datetime, timezone
from utils.logger import setup_logger
from config.settings import (
    SESSION_FILTER_ENABLED,
    ALLOWED_SESSIONS,
    HOUR_FILTER_ENABLED,
    MIN_HOUR_WIN_RATE,
    BEST_HOURS_FILE,
)

logger = setup_logger("session_filter")

_best_hours_cache = None
_best_hours_mtime = None


def _load_best_hours() -> dict | None:
    global _best_hours_cache, _best_hours_mtime

    if not os.path.exists(BEST_HOURS_FILE):
        return None

    try:
        mtime = os.path.getmtime(BEST_HOURS_FILE)
        if _best_hours_cache is not None and mtime == _best_hours_mtime:
            return _best_hours_cache

        with open(BEST_HOURS_FILE) as f:
            _best_hours_cache = json.load(f)
            _best_hours_mtime = mtime
            logger.info(f"Loaded best hours from {BEST_HOURS_FILE}")
            return _best_hours_cache
    except Exception as e:
        logger.warning(f"Could not load {BEST_HOURS_FILE}: {e}")
        return None


def is_valid_session() -> bool:
    if not SESSION_FILTER_ENABLED:
        return True

    now_utc = datetime.now(timezone.utc)
    now_str  = now_utc.strftime("%H:%M")
    hour     = now_utc.hour

    # Layer 1: Time window
    in_window = False
    for session in ALLOWED_SESSIONS:
        if session["start"] <= now_str <= session["end"]:
            in_window = True
            break

    if not in_window:
        logger.debug(f"Outside session windows. UTC: {now_str}")
        return False

    # Layer 2: Hour win-rate filter
    if HOUR_FILTER_ENABLED:
        best_hours = _load_best_hours()

        if best_hours is not None:
            hour_data = best_hours.get(str(hour), {})
            win_rate  = hour_data.get("win_rate", 0)
            trades    = hour_data.get("trades", 0)

            if trades >= 5 and win_rate < MIN_HOUR_WIN_RATE:
                logger.debug(
                    f"Hour {hour:02d}:00 UTC blocked — WR {win_rate:.1f}% "
                    f"< {MIN_HOUR_WIN_RATE}% ({trades} trades)"
                )
                return False

    return True
