"""
research/tools/build_readme.py - regenerate README.md from the repo itself.

Every parameter comes from config/settings.py, sync/watchdog.py, utils/logger.py
and backtest/lsc_engine.py at import time; the validated metrics are parsed from
research/lsc_validation_<date>.txt (the saved output of the frozen-bar backtest);
the live file tree is walked from disk. Nothing that can drift is typed in here.

    python research/tools/build_readme.py          # rewrites README.md
    python research/tools/build_readme.py --check  # exit 1 if README.md is stale
"""
import contextlib
import io
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)
# settings.py fails fast without MT5_LOGIN; the value is irrelevant to the README.
os.environ.setdefault("MT5_LOGIN", "0")

with contextlib.redirect_stdout(io.StringIO()):          # silence the config banner
    import MetaTrader5 as mt5
    from config import settings as S
    import sync.watchdog as W
    import utils.logger as L
    import backtest.lsc_engine as E

PY_MIN = "3.10"   # documented requirement; not derivable from the repo

# ── Validated metrics: parsed from the saved backtest output ────────────────
val_files = sorted(ROOT.glob("research/lsc_validation_*.txt"))
assert val_files, "no research/lsc_validation_*.txt found"
VAL = val_files[-1]
VAL_DATE = re.search(r"(\d{4}-\d{2}-\d{2})", VAL.name).group(1)
val_text = VAL.read_text(encoding="utf-8")
m = re.search(
    r"\[calibrator \$50K/1:10/0\.045%\] trades=(\d+) PF=([\d.]+) WR=([\d.]+)% "
    r"net=\$([-\d.]+) maxDD=([\d.]+)% final=\$([-\d.]+)", val_text)
assert m, f"could not parse the $50K/1:10/0.045% line in {VAL.name}"
TRADES, PF, WR, NET, MAXDD, FINAL = int(m[1]), float(m[2]), float(m[3]), float(m[4]), float(m[5]), float(m[6])
bars = re.search(r"([\d,]+) bars frozen (\S+ \S+) -> (\S+ \S+) UTC", val_text)
assert bars, "bars/date-range line missing"
BARS, D_FROM, D_TO = bars[1], bars[2], bars[3]
assert abs(S.RISK_PERCENT - 0.045) < 1e-9, \
    "validation file is for 0.045% but settings.RISK_PERCENT changed - rerun the backtest"

# ── Live file tree: walked from disk, described here, cross-checked both ways ──
DESC = {
    "main.py":                       "Live loop: one LSC signal check per closed M15 bar",
    "config/__init__.py":            "",
    "config/settings.py":            "Single source of truth for every parameter below",
    "config/settings_diagnostic.py": "Isolated diagnostic-account config (own MAGIC, MT5_DIAGNOSTIC_* creds)",
    "config/.env.example":           "Template for config/.env (git-ignored)",
    "strategy/__init__.py":          "",
    "strategy/lsc_m15.py":           "The strategy: precompute() + check_entry(), pure functions on a DataFrame",
    "backtest/__init__.py":          "",
    "backtest/lsc_engine.py":        "LSC's exact backtest harness (main.py also imports compute_atr14 from it)",
    "risk/__init__.py":              "",
    "risk/trade_manager.py":         "Order send, margin-safe lot sizing, closed-trade detection",
    "risk/circuit_breaker.py":       "Consecutive-loss / daily-loss pause, resets at midnight UTC",
    "utils/__init__.py":             "",
    "utils/mt5_connection.py":       "connect / disconnect",
    "utils/filters.py":              "Spread filter + news filter wrapper",
    "utils/news_filter.py":          "Finnhub high-impact US event blackout (fails closed)",
    "utils/notifications.py":        "WhatsApp (CallMeBot) alerts",
    "utils/logger.py":               "Per-process rotating log file + console",
    "sync/watchdog.py":              "Supervisor: starts and restarts the three live processes",
    "sync/trade_sync.py":            "Writes jasons/ state files, hourly WhatsApp summary",
    "sync/firebase_push.py":         "Pushes jasons/ state to Firebase for remote monitoring",
    "tools/preflight_check.py":      "Go / no-go checker run before launch",
    ".gitignore":                    "",
    "CLAUDE.md":                     "",
    "README.md":                     "Generated by research/tools/build_readme.py",
    "requirements.txt":              "Live dependencies only",
}
live = []
for p in sorted(ROOT.rglob("*")):
    rel = p.relative_to(ROOT).as_posix()
    if not p.is_file() or rel.startswith((".git/", "research/", "logs/", "jasons")) or "__pycache__" in rel:
        continue
    live.append(rel)
missing_desc = [f for f in live if f not in DESC]
gone = [f for f in DESC if not (ROOT / f).exists()]
assert not missing_desc and not gone, \
    f"tree drift - undescribed: {missing_desc}, described but missing: {gone}"
LIVE_COUNT = len(live)
tree_lines = [f"{f:<34}{DESC[f]}".rstrip() for f in live if not f.endswith("__init__.py")]
research_count = sum(1 for p in (ROOT / "research").rglob("*.py"))

# ── Assemble ────────────────────────────────────────────────────────────────
sessions = " and ".join(f"{s['start']}–{s['end']}" for s in S.ALLOWED_SESSIONS)
procs = ", ".join(v.relative_to(ROOT).as_posix() for v in W.PROCESSES.values())
tf = {mt5.TIMEFRAME_M15: "M15"}.get(S.SIGNAL_TIMEFRAME, str(S.SIGNAL_TIMEFRAME))
tree_block = "\n".join(tree_lines)
symbol_badge = S.SYMBOL.replace(".", "%2E")

README = f"""# MIDAS — Liquidity-Sweep Continuation

![Python](https://img.shields.io/badge/Python-{PY_MIN}%2B-blue?style=flat-square&logo=python)
![Platform](https://img.shields.io/badge/Platform-MetaTrader%205-brightgreen?style=flat-square)
![Asset](https://img.shields.io/badge/Asset-{symbol_badge}%20Gold-gold?style=flat-square)
![Status](https://img.shields.io/badge/Status-Stage%204%20%C2%B7%20validated%2C%20pre--live-orange?style=flat-square)
![License](https://img.shields.io/badge/License-Private-red?style=flat-square)

Single-strategy algorithmic gold bot for MetaTrader 5, built to run unattended
24/7 on a dedicated Windows box. One entry point (`main.py`), one validated
strategy (`strategy/lsc_m15.py`), {LIVE_COUNT} files on the live path.

The earlier dual-bot system (Bot 1 structural bias + Bot 2 volatility regime)
was retired after proper backtesting found no edge. LSC is the strategy that
survived in-sample / out-of-sample validation, split-window checks and a
1000-shuffle Monte Carlo stress test.

> **This README is generated.** Every parameter and metric below is read from
> `config/settings.py`, `sync/watchdog.py`, `utils/logger.py` and
> `research/{VAL.name}` by `research/tools/build_readme.py`. Re-run it after
> changing any of them; `--check` exits 1 if it is stale.

---

## Validated performance

Frozen-data backtest, {BARS} {tf} bars of `{S.SYMBOL}` ({D_FROM} → {D_TO} UTC),
run {VAL_DATE}. Both harnesses (the calibrator loop and `backtest/lsc_engine.py`)
reproduce the same trade list; the hash is checked after every refactor.

| Metric | Value |
|--------|-------|
| Account / leverage | $50,000 at 1:10 |
| Risk per trade | {S.RISK_PERCENT}% (margin-capped) |
| Drawdown wall calibrated against | 6% trailing |
| Trades | {TRADES:,} |
| Profit factor | **{PF:.2f}** |
| Win rate | {WR:.1f}% |
| Net P&L | ${NET:,.2f} |
| Max drawdown | {MAXDD:.2f}% |
| Final balance | ${FINAL:,.2f} |

Read that PF for what it is: a thin, positive edge at a risk setting chosen so
the worst of 1000 shuffled sequences stays inside the drawdown wall, not a
money machine. Full output: `research/{VAL.name}`.

---

## How it trades

When price sweeps beyond the prior UTC day's high or low and then **closes
convincingly beyond that level in the sweep direction**, LSC treats it as
continuation, not exhaustion, and enters on the next bar with a static SL/TP.

| Parameter | Value | Source in `config/settings.py` |
|-----------|-------|--------------------------------|
| Symbol / timeframe | `{S.SYMBOL}` / {tf} | `SYMBOL`, `SIGNAL_TIMEFRAME` |
| Close-beyond confirmation | {S.CLOSE_BEYOND_ATR_MULT} × ATR{S.ATR_PERIOD} past the prior-day level | `CLOSE_BEYOND_ATR_MULT` |
| Stop loss | prior-day level ∓ {S.SL_BUFFER_ATR_MULT} × ATR{S.ATR_PERIOD} | `SL_BUFFER_ATR_MULT` |
| Take profit | {S.REWARD_RATIO} × SL distance | `REWARD_RATIO` |
| Cooldown after a trade | {S.COOLDOWN_BARS} bars | `COOLDOWN_BARS` |
| Max trades per day | {S.MAX_TRADES_PER_DAY} | `MAX_TRADES_PER_DAY` |
| Session (UTC) | {sessions} | `ALLOWED_SESSIONS` → `SESSION_HOURS` |
| Hard time exit | {S.MAX_TRADE_HOURS_HARD} h (backtest hold cap {E.MAX_HOLD_BARS} bars) | `MAX_TRADE_HOURS_HARD` |
| Friday | no entries from {S.FRIDAY_CUTOFF_HOUR}:00 UTC, force-flat from {S.FRIDAY_CLOSE_HOUR}:00 UTC | `FRIDAY_CUTOFF_HOUR`, `FRIDAY_CLOSE_HOUR` |
| Loop interval | {S.LOOP_INTERVAL_SECONDS} s (signal evaluated once per closed bar) | `LOOP_INTERVAL_SECONDS` |

The live loop and the backtest call the **same** `precompute()` / `check_entry()`
and read the same `SESSION_HOURS`; there is no separate live approximation.

---

## Architecture

```mermaid
flowchart LR
    WD[sync/watchdog.py<br/>supervisor] -->|starts, restarts, alerts| M[main.py]
    WD --> TS[sync/trade_sync.py]
    WD --> FB[sync/firebase_push.py]
    M --> F[utils/filters.py<br/>spread + news]
    M --> STR[strategy/lsc_m15.py<br/>check_entry]
    STR --> TM[risk/trade_manager.py<br/>margin-safe sizing, order_send]
    TM --> CB[risk/circuit_breaker.py]
    TM --> MT5[(MetaTrader 5)]
    TS --> MT5
    TS --> J[(jasons/*.json)]
    FB --> J
    FB --> FIRE[(Firebase RTDB)]
    M -. WhatsApp .-> WA((CallMeBot))
    WD -. WhatsApp .-> WA
```

One command runs the box. The watchdog starts {procs}, pins their working
directory to the repo root, restarts any that exit with exponential back-off
({W.RESTART_DELAY_MIN} s doubling to {W.RESTART_DELAY_MAX} s, reset after {W.HEALTHY_AFTER} s of healthy uptime,
**no restart cap**), sends a WhatsApp alert on every restart, and terminates all
three when it is stopped. `main.py` itself never gives up on MT5 either: it
reconnects with back-off ({S.RECONNECT_DELAY_MIN} s doubling to {S.RECONNECT_DELAY_MAX} s) and alerts on outage
start and recovery.

```bash
python sync/watchdog.py
```

Logs: `logs/<process>.log`, rotated at midnight UTC, {L.ROTATION_BACKUP_DAYS} days kept.
Runtime state: `jasons/` (git-ignored).

<details>
<summary><strong>Live file structure ({LIVE_COUNT} files, walked from disk)</strong></summary>

```
{tree_block}
```

`research/` holds {research_count} Python files of dev tooling (risk calibrator, backtest
engines, the strategy tournament and its results) that never run on the live
box. See `research/requirements.txt`.

</details>

---

## Safety mechanisms

| Mechanism | Trigger | Action |
|-----------|---------|--------|
| Circuit breaker | {S.MAX_CONSECUTIVE_LOSSES} consecutive losses OR {S.MAX_DAILY_LOSS_PCT}% daily loss | No new trades until midnight UTC, WhatsApp alert |
| Spread filter | spread > {S.MAX_SPREAD_POINTS} points | Skip signal |
| News filter | ±{S.NEWS_WINDOW_MINS} min of a high-impact US event, **or feed unavailable** | Skip signal (fails closed) |
| Session filter | outside {sessions} UTC | Skip signal |
| Margin-safe sizing | risk-% lot would use > {S.MARGIN_SAFETY_BUDGET_PCT * 100:.0f}% of equity as margin | Lot capped, computed live from balance / leverage / price |
| Time exit | position open ≥ {S.MAX_TRADE_HOURS_HARD} h | Force close |
| Friday / weekend | after {S.FRIDAY_CUTOFF_HOUR}:00 UTC Friday or any weekend hour | No entries; force-flat after {S.FRIDAY_CLOSE_HOUR}:00 UTC |
| Config fail-fast | `MT5_LOGIN` missing | `config/settings.py` exits at import; nothing prompts for input |

<details>
<summary><strong>Full rule list, in loop order</strong></summary>

1. If the circuit breaker is tripped, do nothing this cycle.
2. Enforce the hard time exit on any open position older than {S.MAX_TRADE_HOURS_HARD} h.
3. Detect positions that closed since the last cycle; record P&L in the breaker and alert.
4. Weekend, or Friday from {S.FRIDAY_CLOSE_HOUR}:00 UTC: force-close everything, stop.
5. Friday from {S.FRIDAY_CUTOFF_HOUR}:00 UTC: no new entries.
6. Daily cap ({S.MAX_TRADES_PER_DAY}) reached, hour outside the session, spread over {S.MAX_SPREAD_POINTS} points, or news blackout: no signal.
7. Fetch {tf} bars; only evaluate when a new bar has closed.
8. `check_entry()`: cooldown ({S.COOLDOWN_BARS} bars), warm-up, then sweep-and-close-beyond test → BUY / SELL / NEUTRAL with SL and TP.
9. Lot = min(risk-% lot, margin-safe ceiling, broker max), floored at broker min, rounded to step.
10. Send the order with the strategy's SL/TP; on success count the trade and alert.

</details>

---

## Setup

- Windows, Python {PY_MIN}+, MetaTrader 5 installed and logged in, `{S.SYMBOL}` visible in Market Watch.
- `pip install -r requirements.txt` on the box; add `-r research/requirements.txt` on a dev machine.
- Copy `config/.env.example` to `config/.env`: MT5 credentials, `FINNHUB_API_KEY`
  (**required**, the news filter fails closed without it), WhatsApp phone + CallMeBot
  key, `FIREBASE_DB_URL`.
- Go / no-go before launch:

```bash
python tools/preflight_check.py                      # production config
python tools/preflight_check.py --config diagnostic  # diagnostic account
```

Exit code 0 = go (warnings allowed), 1 = any FAIL.

---

## Disclaimer

**This is experimental research software, not an investment product.**

- It is provided for educational and personal research purposes only and is
  not financial advice.
- Every figure above is a **hypothetical backtest** on historical data with an
  assumed spread. Backtests do not account for slippage, requotes, outages,
  broker behaviour or regime change, and past performance does not guarantee
  future results.
- Algorithmic trading on leveraged instruments carries a real risk of losing
  the entire account. A profit factor of {PF:.2f} is a thin edge that can turn
  negative in a different market regime.
- The author is not a licensed financial adviser. Never trade with money you
  cannot afford to lose. Use at your own risk.

*Built by James Carragher | MIDAS Capital*
"""

target = ROOT / "README.md"
if "--check" in sys.argv:
    stale = target.read_text(encoding="utf-8") != README
    print("README.md is STALE - run build_readme.py" if stale else "README.md is up to date")
    sys.exit(1 if stale else 0)
target.write_text(README, encoding="utf-8")
print(f"README.md written: {len(README.splitlines())} lines, {LIVE_COUNT} live files, PF {PF:.2f} from {VAL.name}")
